remun = {
    'matricula': 0,
    'nome': 1,
    'cargo': 2,
    'lotacao': 3,
    'rem_cargo': 4,
    'outras_rem_legal_judicial': 5,
    'confianca': 6,
    'grat_natal': 7,
    'ferias_constitucional': 8,
    'abono_permanencia': 9,
    'outras_rem_temporarias': 10,
    'verbas_idenizatorias': 11,
    'brutos': 12,
    'previdenciaria': 13,
    'imposto_renda': 14,
    'teto': 15,
    'total_descontos': 16,
    'total_liquido': 17
}

remun_old = {
    'nome': 0,
    'cargo': 1,
    'folha': 2,
    'lotacao': 3,
    'rem_cargo': 4,
    'outras_rem_legal_judicial': 5,
    'confianca': 6,
    'grat_natal': 7,
    'ferias_constitucional': 8,
    'abono_permanencia': 9,
    'brutos': 10,
    'previdenciaria': 11,
    'imposto_renda': 12,
    'teto': 13,
    'total_descontos': 14,
    'total_liquido': 15,
    'idenizacoes': 16,
    'outras_rem_temporarias': 17
}

ideniz = {
    'matricula': 0,
    'nome': 1,
    'cargo': 2,
    'lotacao': 3,
    'ferias_idenizatorias': 4,
    'alimentacao': 5,
    'creche': 6,
    'transporte': 7,
    'transporte_mobiliario': 8,
    'natalidade': 9,
    'ajuda_custo': 10,
    'aux_moradia': 11,
    'abono_pecuniario': 12,
    'premio_pecunia': 13,
    'total_idenizacoes': 14,
    'grat_pericia_projeto': 15,
    'grat_exercicio_cumulativo': 16,
    'grat_encargo_curso_concurso': 17,
    'grat_local': 18,
    'grat_natal': 19,
    'hora_extra': 20,
    'abono_permanencia': 21,
    'noturno': 22,
    'atividade_penosa': 23,
    'insalubridade': 24,
    'outras_remuneratorias': 25,
    'outras_retroativas_temporarias': 26,
    'ferias': 27,
    'total_temporarias': 28
}
